### ISSUE TITLE
misc recon tracking thread

### ISSUE THREAD

**Issue by nathanshelly** [nathanshelly/.files#55]
various dotfiles related things to investigate

- [ ] https://github.com/zdharma/pm-perf-test - investigate list of plugins tested

**Comment by nathanshelly** [comment]
- [ ] maybe turn on additional python syntax highlighting? https://github.com/vim-python/python-syntax#configuration

**Comment by nathanshelly** [comment]
# git hooks

- [ ] https://github.com/rycus86/githooks
- [ ] https://pre-commit.com/
- [ ] https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/
- [ ] https://github.com/typicode/husky/issues/391

## priorities

- [ ] language-agnostic (`husky` nice for example but don't like the `js` dependence)

## not priorities (at least at the moment)

- [ ] hooks beyond pre-commit

**Comment by nathanshelly** [comment]
reread `zplugin` docs
- [ ] https://github.com/zdharma/zplugin
- [ ] https://github.com/zdharma/zplugin#zplugin-wiki

**Comment by nathanshelly** [comment]
- [ ] https://git-template.readthedocs.io/en/latest/

**Comment by nathanshelly** [comment]
- [ ] https://github.com/trapd00r/LS_COLORS

**Comment by nathanshelly** [comment]
- [ ] macOS tiling window manager - https://github.com/koekeishiya/yabai

**Comment by nathanshelly** [comment]
- [ ] ssh client https://termius.com/

**Comment by nathanshelly** [comment]
- [ ] https://github.com/Vimjas/vint

**Comment by nathanshelly** [comment]
- [ ] maybe switch from [`vim-surround`](https://github.com/tpope/vim-surround) to [`vim-sandwhich`](https://github.com/machakann/vim-sandwich)?
  -  https://joereynoldsaudio.com/2020/01/22/vim-sandwich-is-better-than-surround.html
- [ ] various additional plugins by same author - https://github.com/machakann

**Comment by nathanshelly** [comment]
- [ ] https://github.com/tpope/vim-rails

**Comment by nathanshelly** [comment]
- [ ] https://github.com/zsh-vi-more

**Comment by nathanshelly** [comment]
- [ ] [fzf changelog](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0190)

**Comment by nathanshelly** [comment]
- [ ] https://github.com/zsh-users/zaw

**Comment by nathanshelly** [comment]
- [ ] v

**Comment by nathanshelly** [comment]
- [ ] interesting clis - https://github.com/Byron

**Comment by nathanshelly** [comment]
- [ ] https://github.com/romkatv/powerlevel10k/ - reread docs

**Comment by nathanshelly** [comment]
- [ ] https://github.com/clarity20/fasder

**Comment by nathanshelly** [comment]
- [ ] https://github.com/walles/moar - after https://github.com/walles/moar/issues/21 is resolved

**Comment by nathanshelly** [comment]
- [ ] https://github.com/eth-p/bat-extras

**Comment by nathanshelly** [comment]
- [ ] https://github.com/zdharma/zinit-configs

**Comment by nathanshelly** [comment]
- [ ] https://github.com/lra/mackup

**Comment by nathanshelly** [comment]
- [ ] https://www.peterborgapps.com/lingon/

**Comment by nathanshelly** [comment]
-  [ ] https://github.com/webpro/awesome-dotfiles

**Comment by nathanshelly** [comment]
- [ ] 
![Uploading image.png…]()

**Comment by nathanshelly** [comment]
- [ ] [macOS set default app to open specific file types](https://github.com/mathiasbynens/dotfiles/issues/54)

**Comment by nathanshelly** [comment]
- [ ] https://github.com/MichaelAquilina/zsh-you-should-use

**Comment by nathanshelly** [comment]
- [ ] https://github.com/tjdevries/colorbuddy.nvim

**Comment by nathanshelly** [comment]
- [ ] https://github.com/neoclide/coc-eslint/issues/29

**Comment by nathanshelly** [comment]
- [ ] https://gist.github.com/antifuchs/4d751d182296e2382fc6d86d26e0c25e

**Comment by nathanshelly** [comment]
- [ ] https://github.com/ms-jpq/sad

**Comment by nathanshelly** [comment]
- [ ] https://github.com/nathanshelly/.files/issues/55

**Comment by nathanshelly** [comment]
- [ ] https://github.com/pemistahl/grex

**Comment by nathanshelly** [comment]
- [ ] https://github.com/neovim/nvim-lspconfig

**Comment by nathanshelly** [comment]
- [ ] https://git.sr.ht/~seirdy/dotfiles

**Comment by nathanshelly** [comment]
- [ ] https://github.com/jarun/buku

**Comment by nathanshelly** [comment]
- [ ] https://github.com/romkatv/zsh-bin

**Comment by nathanshelly** [comment]
- [ ] https://github.com/beauwilliams/statusline.lua

**Comment by nathanshelly** [comment]
- [ ] https://github.com/BrianHicks/nix-script

**Comment by nathanshelly** [comment]
- [ ] https://github.com/b3nj5m1n/kommentary

**Comment by nathanshelly** [comment]
- [ ] https://github.com/easymotion/vim-easymotion

**Comment by nathanshelly** [comment]
- [ ] https://github.com/rockerBOO/awesome-neovim

**Comment by nathanshelly** [comment]
- [ ] https://github.com/charmbracelet/glow

**Comment by nathanshelly** [comment]
- [ ] https://github.com/zellij-org/zellij

**Comment by nathanshelly** [comment]
- [ ] https://github.com/ms-jpq/sad
- [ ] https://github.com/chmln/sd

**Comment by nathanshelly** [comment]
- [ ] https://github.com/lincheney/fzf-tab-completion

**Comment by nathanshelly** [comment]
- [ ] https://github.com/sqshq/sampler

**Comment by nathanshelly** [comment]
- [ ] https://github.com/withfig/autocomplete

**Comment by nathanshelly** [comment]
- [ ] https://github.com/jamesob/desk

**Comment by nathanshelly** [comment]
- [ ] https://github.com/bbugyi200/funky

**Comment by nathanshelly** [comment]
- [ ] https://github.com/Mic92/sops-nix

**Comment by nathanshelly** [comment]
- [ ] https://www.raycast.com/

**Comment by nathanshelly** [comment]
- [ ] https://github.com/serhii-londar/open-source-mac-os-apps

**Comment by nathanshelly** [comment]
- [ ] https://github.com/serhii-londar/open-source-mac-os-apps

**Comment by nathanshelly** [comment]
- [ ] https://github.com/marlonrichert/zsh-snap

**Comment by nathanshelly** [comment]
- [ ] https://github.com/mermaid-js/mermaid#readme

**Comment by nathanshelly** [comment]
- [ ] https://fig.io

**Comment by nathanshelly** [comment]
- [ ] https://github.com/Byron/gitoxide

**Comment by nathanshelly** [comment]
- [ ] https://github.com/tj/git-extras

**Comment by nathanshelly** [comment]
- [ ] https://github.com/tailscale-dev/tclip

**Comment by nathanshelly** [comment]
- [ ] https://github.com/bacongravy/macinbox

**Comment by nathanshelly** [comment]
- [ ] https://github.com/Xe/iosevka
